import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full flex justify-between border-b border-black">
          <Link href={"/"}>Home</Link>
          <ul className="flex gap-4">
            <li>
              <Link href={'/todos'}>Todos</Link>
            </li>
            <li>
              <Link href={'/ssgtest'}>SSG</Link>
            </li>
            <li>
              <Link href={'/isrtest'}>ISR</Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
